"""import string

Keys = {'Key.shift_r': '',
        'Key.shift': '',
        'Key.left': '',
        'Key.right': '',
        'Key.up': '',
        'Key.down': '',
        'Key.enter': '\n',
        'Key.backspace': ' ',
        'Key.alt_l': '',
        'Key.alt_gr': '',
        'Key.cmd': '',
        'Key.ctrl_l': '',
        'Key.ctrl_r': '',
        'Key.caps_lock': '',
        'Key.tab': '      ',
        'Key.esc': '',
        'Key.f1': '',
        'Key.f2': '',
        'Key.f3': '',
        'Key.f4': '',
        'Key.f5': '',
        'Key.f6': '',
        'Key.f7': '',
        'Key.f8': '',
        'Key.f9': '',
        'Key.f10': '',
        'Key.f11': '',
        'Key.f12': '',
        'Key.print_screen': '',
        'Key.insert': '',
        'Key.delete': '',
        'Key.space': '  '}

KeysRegex = {'\x1a': '!@',
             '\x01': '!@',
             '\x11': '!@',
             "\x17": '!@',
             '\x13': '!@',
             '\x18': '!@',
             '\x03': '!@',
             '\x04': '!@',
             '\x05': '!@',
             '\x12': '!@',
             '\x06': '!@',
             '\x16': '!@',
             '\x02': '!@',
             '\x07': '!@',
             '\x14': '!@',
             '\x19': '!@',
             '\x08': '!@',
             '\x0e': '!@',
             '\r': '!@',
             '\x15': '!@',
             '\x0b': '!@',
             '<188>': '!@',
             '<190>': '!@',
             '\x0c': '!@',
             '\x0f': '!@',
             '\x10': '!@',
             '<186>': '!@',
             '<191>': '!@',
             '<222>': '!@',
             '\x1b': '!@'}

Hebrew = {"ש": "a",
          "ז": "z",
          "'": "w",
          "ד": "s",
          "ס": "x",
          "ב": "c",
          "ג": "d",
          "ק": "e",
          "ה": "v",
          "כ": "f",
          "ר": "r",
          "נ": "b",
          "ע": "g",
          "א": "t",
          "מ": "n",
          "י": "h",
          "ט": "y",
          "צ": "m",
          "ח": "j",
          "ו": "u",
          "ת": ",",
          "ל": "k",
          "ן": "i",
          "ץ": ".",
          "ך": "l",
          "ם": "o",
          "ף": ";",
          "פ": "p",
          " ": " "}

digit = {k: k for k in string.digits}
punctuation = {k: k for k in string.punctuation}
listTexts = ["search in computer",
             "check nameOfComputer",
             "scan Your router ",
             "Have you functions  to make to you easy!",
             "define Folder For You",
             "and More Functions!",
             "simple calculator",
             "Connect To Others Devices!"]

COLORS = ['SlateBlue4',
          'red', 'blue',
          'black', 'green',
          'CadetBlue3',
          'blue2', 'black',
          'blue4', 'RoyalBlue2',
          'RoyalBlue3', 'RoyalBlue4',
          'DodgerBlue2', 'DodgerBlue3',
          'DodgerBlue4', 'SteelBlue1',
          'SteelBlue2', 'SteelBlue3',
          'SteelBlue4', 'DeepSkyBlue2',
          'DeepSkyBlue3', 'DeepSkyBlue4',
          'SkyBlue1', 'black',
          'SkyBlue2', 'SkyBlue3',
          'SkyBlue4', 'PaleTurquoise2',
          'SlateGray1', 'SlateGray2',
          'SlateGray3', 'SlateGray4',
          'cyan2', 'cyan3',
          'LightCyan2', 'LightCyan3',
          'black', 'LightCyan4',
          'PaleTurquoise1',
          'PaleTurquoise3', 'PaleTurquoise4',
          'black', 'CadetBlue1',
          'CadetBlue2', 'CadetBlue4',
          'turquoise1', 'turquoise2',
          'turquoise3', 'turquoise4',
          'cyan4', 'DarkSlateGray1',
          'DarkSlateGray2', 'DarkSlateGray3',
          'DarkSlateGray4']

listOfName = ["The Incredible Hulk",
              "Forest Philosopher",
              "An angel in a white robe",
              "A researcher of heaven",
              "The mesmerized cat",
              "White hacker",
              "A prince without a kingdom",
              "The Dwarf Witch",
              "A very smart man"]

"""

import string


HebrewAndAllKeyboard = "שזדסבגקהכרנעאמיטצחותלןץךםףפ"+string.printable
Stack = {f"|{str(k+100)}|K": v for k, v in zip(range(len(HebrewAndAllKeyboard)), HebrewAndAllKeyboard)}

Keys = {'Key.shift_r': '',
        'Key.shift': '',
        'Key.left': '',
        'Key.right': '',
        'Key.up': '',
        'Key.down': '',
        'Key.enter': '\n',
        'Key.backspace': '!<',
        'Key.alt_l': '',
        'Key.alt_gr': '',
        'Key.cmd': '',
        'Key.ctrl_l': '',
        'Key.ctrl_r': '',
        'Key.caps_lock': '',
        'Key.tab': '      ',
        'Key.esc': '',
        'Key.f1': '',
        'Key.f2': '',
        'Key.f3': '',
        'Key.f4': '',
        'Key.f5': '',
        'Key.f6': '',
        'Key.f7': '',
        'Key.f8': '',
        'Key.f9': '',
        'Key.f10': '',
        'Key.f11': '',
        'Key.f12': '',
        'Key.print_screen': '',
        'Key.insert': '',
        'Key.delete': '',
        'Key.space': '  '}

KeysRegex = {'\x1a': '!@',
             '\x01': '!@',
             '\x11': '!@',
             "\x17": '!@',
             '\x13': '!@',
             '\x18': '!@',
             '\x03': '!@',
             '\x04': '!@',
             '\x05': '!@',
             '\x12': '!@',
             '\x06': '!@',
             '\x16': '!@',
             '\x02': '!@',
             '\x07': '!@',
             '\x14': '!@',
             '\x19': '!@',
             '\x08': '!@',
             '\x0e': '!@',
             '\r': '!@',
             '\x15': '!@',
             '\x0b': '!@',
             '<188>': '!@',
             '<190>': '!@',
             '\x0c': '!@',
             '\x0f': '!@',
             '\x10': '!@',
             '<186>': '!@',
             '<191>': '!@',
             '<222>': '!@',
             '\x1b': '!@'}

Hebrew = {"ש": "a",
          "ז": "z",
          "ד": "s",
          "ס": "x",
          "ב": "c",
          "ג": "d",
          "ק": "e",
          "ה": "v",
          "כ": "f",
          "ר": "r",
          "נ": "b",
          "ע": "g",
          "א": "t",
          "מ": "n",
          "י": "h",
          "ט": "y",
          "צ": "m",
          "ח": "j",
          "ו": "u",
          "ת": ",",
          "ל": "k",
          "ן": "i",
          "ץ": ".",
          "ך": "l",
          "ם": "o",
          "ף": ";",
          "פ": "p",
          " ": " "}

listTexts = ["search in computer",
             "check nameOfComputer",
             "scan Your router ",
             "Have you functions  to make to you easy!",
             "define Folder For You",
             "and More Functions!",
             "simple calculator",
             "Connect To Others Devices!"]

COLORS = ['SlateBlue4',
          'red', 'blue',
          'black', 'green',
          'CadetBlue3',
          'blue2', 'black',
          'blue4', 'RoyalBlue2',
          'RoyalBlue3', 'RoyalBlue4',
          'DodgerBlue2', 'DodgerBlue3',
          'DodgerBlue4', 'SteelBlue1',
          'SteelBlue2', 'SteelBlue3',
          'SteelBlue4', 'DeepSkyBlue2',
          'DeepSkyBlue3', 'DeepSkyBlue4',
          'SkyBlue1', 'black',
          'SkyBlue2', 'SkyBlue3',
          'SkyBlue4', 'PaleTurquoise2',
          'SlateGray1', 'SlateGray2',
          'SlateGray3', 'SlateGray4',
          'cyan2', 'cyan3',
          'LightCyan2', 'LightCyan3',
          'black', 'LightCyan4',
          'PaleTurquoise1',
          'PaleTurquoise3', 'PaleTurquoise4',
          'black', 'CadetBlue1',
          'CadetBlue2', 'CadetBlue4',
          'turquoise1', 'turquoise2',
          'turquoise3', 'turquoise4',
          'cyan4', 'DarkSlateGray1',
          'DarkSlateGray2', 'DarkSlateGray3',
          'DarkSlateGray4']

listOfName = ["The Incredible Hulk",
              "Forest Philosopher",
              "An angel in a white robe",
              "A researcher of heaven",
              "The mesmerized cat",
              "White hacker",
              "A prince without a kingdom",
              "The Dwarf Witch",
              "A very smart man"]


